/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
     kotlin("jvm") version "1.7.10"
    `java-library`
    `maven-publish`
   // To generate JARs
}
group = "com.dhilip"              // Your group/package
version = "1.0.0"
repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
tasks.register<Jar>("createJar") {
    archiveBaseName.set("totp-generator")       // Name of the JAR file
    archiveVersion.set("1.0.0")            // Version of the JAR
    from(project.the<JavaPluginConvention>().sourceSets["main"].output)
    // Include compiled Kotlin class files
}




dependencies {
    implementation("commons-codec:commons-codec:1.15")
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // This dependency is used by the application.
    implementation(libs.guava)
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
